"""Add missing migrations

Revision ID: dbb4565a528e
Revises: e75228e80dc5
Create Date: 2026-01-14 11:55:36.249487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb4565a528e'
down_revision = 'e75228e80dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('account_type', sa.Enum('TENANT', 'PROPERTY_OWNER', 'ADMINISTRATOR', name='accounttype'), nullable=False),
    sa.Column('token_2fa', sa.String(length=1024), nullable=True),
    sa.Column('is_2fa_auth_enabled', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=60), nullable=False),
    sa.Column('square_footage', sa.Integer(), nullable=False),
    sa.Column('rent_per_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Properties')
    op.drop_table('Users')
    # ### end Alembic commands ###
